- name: tiller-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    state: present
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: tiller-apb
    playbook_debug: false
